Trim white spaces when reading private key
This solves a common problem when there is an extra new-line in the
private key file. For instance:

    Error: stylus deploy failed

    Caused by:
       0: failed to load wallet
       1: invalid private key
       2: Odd number of digits